name: Deploy LoopBack Backend to Google Cloud Run

on:
  push:
    branches:
      - [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and deploy Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/loopback-api
          gcloud run deploy loopback-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/loopback-api \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
